# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://erc-bpgc.github.io/blog/"
DefaultContentLanguage  = "en"
title                   = "The ERC Blog"
theme                   = "hugo-future-imperfect-slim"
paginate                = 8
disqusShortname         = ""
googleAnalytics         = "UA-173174352-2"
pluralizeListTitles     = false
disableLanguages        = []
publishDir				= "docs"

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "../blog"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "Blog for the Electronics and Robotics Club of BITS Goa."
    author              = "ERC"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "the erc blog"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = false

  [params.intro]
    header                = "the erc blog"
    paragraph             = "By the Electronics and Robotics Club"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/ARM.png"
      shape               = "circle"
      width               = ""
      alt                 = "Hugo Future Imperfect Slim"

  [params.sidebar]
    about               = "The Blog for the Electronics and Robotics Club of BITS Goa. Welcome!"
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "../blog/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "../blog/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2


[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

[social]
  # Coding Communities
  github                = "ERC-BPGC"
  gitlab                = ""
  stackoverflow         = "" 
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = ""
  linkedin_company      = "electronics-robotics-club-bits-goa/"
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = "ElectronicsAndRoboticsClub"
  googleplus            = ""
  reddit                = ""
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = "erc_bitsgoa/"
  tumblr                = ""
  twitter               = "erc_bpgc?s=12"
  strava                = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = ""
  mastodon              = ""
  # Email
  email                 = ""
